services:
  ollama:
    image: ollama/ollama:0.9.0
    container_name: ollama-server
    ports:
      - "51134:11434"   # Host port 51134 → Container port 11434
    volumes:
      - ${OLLAMA_LOCAL_MODELS_PATH:-ollama_data}:/root/.ollama
    restart: unless-stopped

  shinyapp:
    build:       # Build the Shiny app image from the Dockerfile in the current directory, OR use the pre-built image from GitHub Container Registry for faster startup
      context: .
      dockerfile: Dockerfile
    #image: ghcr.io/pandora-isomemo/llmmodule:main  # Uncomment this line to use the pre-built image from GitHub Container Registry for faster startup
    container_name: shiny-llm-app
    ports:
      - "3838:3838"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
